apiVersion: v1
kind: Namespace
metadata:
  name: outhouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outhouse-api
  namespace: outhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outhouse-api
  template:
    metadata:
      labels:
        app: outhouse-api
    spec:
      containers:
      - name: outhouse-api
        image: janheindejong/outhouse-api:487ea35-arm64
        env:
        - name: DB_URL
          value: "mariadb+pymysql://root:mariadb@mariadb.mariadb/outhouse"
        ports:
        - containerPort: 8000
          name: http-port
        resources:
          limits:
            cpu: 500m
            memory: 150Mi
          requests:
            cpu: 500m
            memory: 150Mi
      initContainers:
      - name: db-init 
        image: janheindejong/outhouse-api:487ea35-arm64
        command: ["sh", "-c", "alembic upgrade head"]
        env:
        - name: DB_URL
          value: "mariadb+pymysql://root:mariadb@mariadb.mariadb/outhouse"    
---
apiVersion: v1
kind: Service
metadata:
  name: outhouse-api
  namespace: outhouse
spec:
  type: ClusterIP
  selector:
    app: outhouse-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: http-port
