name: backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

env:
  DOTNET_VERSION: '8.x'

jobs:
  test: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Start SQL Server in Docker container
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine
          sa-password: 'yourStrong(!)Password'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test

  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:

      # Checkout repository 
      - name: Checkout
        uses: actions/checkout@v4

 # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      
      # Run dotnet build and publish
      - name: Build and publish
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet publish -c Release --property:PublishDir='./myapp' 
          
      # Deploy to Azure Web apps
      - name: Deploy
        uses: azure/webapps-deploy@v3
        with: 
          app-name: outhouse # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: './myapp'      
