name: backend

on:
  push:
    branches:
      - main
    paths: 
      - 'backend/**'
  pull_request:
    branches:    
      - main
    paths: 
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:

      # Checkout repository 
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Python environment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      # Install dependencies
      - name: Install dependencies 
        run: poetry install --sync

      # Run tests
      - name: Run tests 
        run: poetry run scripts/test.sh 

  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./backend
    if: github.event_name != 'pull_request'
    steps:

      # Checkout repository 
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Docker environment
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          platforms: arm64,amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/our-cottage-api:latest
